export const GET_CAR2GO_CARS = 'car/GET_CAR2GO_CARS'
export const GET_EVO_CARS = 'car/GET_EVO_CARS'
export const SET_CAR2GO_VISIBILITY = 'car/SET_CAR2GO_VISIBILITY'
export const SET_EVO_VISIBILITY = 'car/SET_EVO_VISIBILITY'
